name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |            - name: Run Authzed Test Server
  # You may pin to the exact commit or the version.
  # uses: authzed/action-testserver@f8a5a3c34f6d8ef0e64577c802d39728bdf406eb
  uses: authzed/action-testserver@v3
  with:
    # Version of `zed testserver` to use
    version: # optional, default is latest
          
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
